# Generated by Django 4.1 on 2022-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waspbt_djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("LW", "Low"), ("MD", "Medium"), ("HG", "High")],
                default="LW",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("TD", "To do"), ("IP", "In progress"), ("FI", "Finished")],
                default="TD",
                max_length=2,
            ),
        ),
    ]
