# Generated by Django 4.1 on 2022-08-24 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("waspbt_djangoapp", "0002_alter_issue_priority_alter_issue_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
